/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lab".
 */
export interface Lab {
  id: string;
  open: boolean;
  event?: string | Event;
  members?: string[] | Member[];
  schedule?: string | Schedule;
  odoo: {
    contractId?: number;
  };
  settings: {
    gatekeeper: {
      acceptSound?: string | Media;
      rejectSound?: string | Media;
    };
    labOpenImage?: string | Media;
    labClosedImage?: string | Media;
    startupLabWhenFirstCheckIn?: boolean;
    shutdownLabWhenAllCheckedOut?: boolean;
    notifyStatus?: boolean;
    notifyLeadershipCheckInOut?: boolean;
    rolesToAnnounce?: string[] | Role[];
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  name?: string;
  type?: 'Workshop' | 'Interest Meeting' | 'Speaker Event' | 'Game Night' | 'Tournament' | 'Field Trip' | 'Other';
  location?: string;
  startDate?: string;
  endDate?: string;
  imageUrl?: string;
  description?: string;
  terplink: {
    eventId?: string;
    accessCode?: string;
  };
  discord: {
    eventId?: string;
    messageId?: string;
  };
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  name?: string;
  nickname?: string;
  birthday?: string;
  email?: string;
  isClubMember?: boolean;
  roles?: string[] | Role[];
  profile: {
    picture?: string | Media;
    links: {
      type: string | Integration;
      url: string;
      id?: string;
    }[];
    bio?: string;
  };
  umd: {
    directoryId?: string;
    cardSerial?: string;
    terplink: {
      accountId?: string;
      issuanceId?: string;
      communityId?: string;
    };
  };
  integrations: {
    discord?: string;
    oculus?: string;
    steam?: string;
    scoresaber?: string;
  };
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  name: string;
  color?: string;
  priority: number;
  discordRoleId?: string;
  discordEmoji?: string;
  isLeadership: boolean;
  isSelfAssignable: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  isPublic?: boolean;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: string;
  name?: string;
  discordEmoji?: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: string;
  name?: string;
  time: (
    | {
        day?: 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';
        allday?: boolean;
        from?: string;
        to?: string;
        reason?: string;
        id?: string;
        blockName?: string;
        blockType: 'Closing';
      }
    | {
        day?: 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';
        allday?: boolean;
        from?: string;
        to?: string;
        staff?: string[] | Member[];
        id?: string;
        blockName?: string;
        blockType: 'Opening';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bot".
 */
export interface Bot {
  id: string;
  enabled?: boolean;
  auth: {
    clientId?: string;
    clientSecret?: string;
    token?: string;
  };
  media: {
    banner?: string | Media;
  };
  guild: {
    guildId?: string;
    channels: {
      announcements?: string;
      lab?: string;
      notifications?: string;
      inventory?: string;
      audit?: string;
      events?: string;
      leadership?: string;
    };
    statusChannels: {
      lab: {
        channelId?: string;
        messages: {
          messageId: string;
          id?: string;
        }[];
      };
      inventory: {
        channelId?: string;
        messages: {
          messageId: string;
          id?: string;
        }[];
      };
      leadership: {
        channelId?: string;
        messages: {
          messageId: string;
          id?: string;
        }[];
      };
      roles: {
        channelId?: string;
        messages: {
          messageId: string;
          id?: string;
        }[];
      };
    };
    notificationRoles: {
      lab?: string | Role;
      workshop?: string | Role;
      project?: string | Role;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cas".
 */
export interface CAS {
  id: string;
  username?: string;
  password?: string;
  duoDeviceName?: string;
  hotpSecret?: string;
  hotpCounter?: number;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist".
 */
export interface Wishlist {
  id: string;
  wishlist: {
    type?: string | Description;
    quantity?: number;
    id?: string;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "descriptions".
 */
export interface Description {
  id: string;
  name: string;
  image?: string | Media;
  type:
    | 'h_vr'
    | 'h_ar'
    | 'h_xr'
    | 'h_vr_accessory'
    | 'h_pc'
    | 'h_laptop'
    | 'h_console'
    | 'h_phone'
    | 'h_misc'
    | 's_game'
    | 's_software';
  description?: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "odoo".
 */
export interface Odoo {
  id: string;
  url?: string;
  db?: string;
  uid?: number;
  password?: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  casManager?: boolean;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: string;
  description: string | Description;
  status: 'inLab' | 'checkedOut';
  public: boolean;
  serial?: string;
  umdSerial?: string;
  mac?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heartbeats".
 */
export interface Heartbeat {
  id: string;
  device?: string | Device;
  date?: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number];
  battery: {
    level?: number;
    charging?: boolean;
  };
  network: {
    ipAddress?: string;
    wifi: {
      current: {
        ssid?: string;
        bssid?: string;
        level?: number;
      };
      nearbyNetworks: {
        ssid?: string;
        bssid?: string;
        level?: number;
        id?: string;
      }[];
    };
  };
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendances".
 */
export interface Attendance {
  id: string;
  member?: string | Member;
  date?: string;
  event?: string | Event;
  type?: 'in' | 'out';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  title?: string;
  content?: {
    [k: string]: unknown;
  }[];
  sentMessages: {
    messageId?: string;
    id?: string;
  }[];
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software".
 */
export interface Software {
  id: string;
  type?: string | Description;
  availableOn?: string[] | Device[];
  publish?: boolean;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name?: string;
  status?: 'Proposed' | 'Active' | 'Inactive' | 'Finished';
  projectLeads?: string[] | Member[];
  members?: string[] | Member[];
  logo?: string | Media;
  banner?: string | Media;
  gallery: {
    image?: string | Media;
    description?: string;
    id?: string;
  }[];
  startDate?: string;
  endDate?: string;
  description?: {
    [k: string]: unknown;
  }[];
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: string;
  title?: string;
  open?: boolean;
  allowRevote?: boolean;
  author?: string;
  messages: {
    channel?: string;
    msg?: string;
    id?: string;
  }[];
  choices: {
    name?: string;
    voters: {
      id?: string;
    }[];
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: string;
  date?: string;
  count: {
    discord?: number;
    terplink?: number;
    youtube?: number;
    instagram?: number;
    twitter?: number;
  };
  createdAt: string;
  updatedAt: string;
}
